### ISSUE TITLE
Differents channels to dfifferents services

### ISSUE THREAD

**Issue by CaBeTuX** [nisabek/icinga2-slack-notifications#14]
Hi Team, 

I know that this isn't' a issue, but maybe you can help me on this or create a request for this feature.

I need send notifications to differents Slack channels depending the type of the service/check. I can set the service to will notify differents users but I cant configure differents channels depending the user in the slack-notifications-configuration...

It's possible actually or is necessary add changes into the configs and templates?

Thanks in advance! :)

Cheers!

**Comment by nisabek** [comment]
Hi CaBeTuX,

Thanks for using our plugin! 
The plugin settings can be configured using the Notification templates, e.g. below I have configured the host and service to have different tokens and channels:

```
apply Notification "slack-notifications-notification-hosts" to Host {
  import "slack-notifications-user-configuration-hosts"
  vars.slack_notifications_webhook_url = "my_webhook_for_hosts"
  vars.slack_notifications_channel = "#icinga2-test-host"

  assign where host.vars.slack_notifications == "enabled"
}

apply Notification "slack-notifications-notification-services" to Service {
  import "slack-notifications-user-configuration-services"
  vars.slack_notifications_channel = "#icinga2-test"

  assign where service.vars.slack_notifications == "enabled"
}
```

Now, I assume, if you have different templates for your Services, you can create different Notification templates for those services and configure the channels respectively.

I don't have a more sophisticated config at hand that would allow me to easily test what I mean, but maybe this gives you an idea on how to configure that.

Let me know how it goes, perhaps share some of your configs with different services and I can test with them.

Thanks and Regards,
Nune

**Comment by nisabek** [comment]
any news here?...

**Comment by nisabek** [comment]
inactive...
