### ISSUE TITLE
Possible to suppress Warnings?

### ISSUE THREAD

**Issue by Seegras** [nisabek/icinga2-slack-notifications#21]
I'm not quite sure whether this is a support-question or a feature request. 

Is it possible to suppress notifications for warnings? 
Because I'd like to see only criticals (and their associated recoveries) in slack. 

Thanks

**Comment by shsubramanian** [comment]
You can remove the "Warning" state from slack-notifications-configuration.conf

`template Notification "slack-notifications-default-configuration-services" {
    import "slack-notifications-configuration"

    states = [ OK, Warning, Critical, Unknown ]
}`

**Comment by nisabek** [comment]
@Seegras please reopen in case this did not answer your question. @shsubramanian thanks for your reply!
