### ISSUE TITLE
how to use this in director mode ?

### ISSUE THREAD

**Issue by sarojamarraj** [nisabek/icinga2-slack-notifications#22]
1) how to use this in director mode?
2) I'm getting similar host and service notification non-stop, from where can I tweak the delay or time out?

**Comment by winem** [comment]
1) I would just deploy the scripts from the git repository. It works fine if you drop the `slack-notifications-*` configuration files in a global-zone to make it available to all nodes or just the zone of the node where you want these notifications to be available. All you have to do then is to set `vars.slack_notifications = "enabled"` in the host or service object. 

2) The interval in the notification object specifies the interval between notifications if there was no state change. In this case it is set via in the `slack-notifications-default-configuration` template in `slack-notifications-configuration.conf`. But you say "similiar host an service notification". What exactly does this mean? Each host-service-set is handled on it's own and they are independent of each other. 
Another thing you might want to check is the flapping detection if it's really for the same host and service all the time. Enabling the flapping detection will send out just a single notification when a service starts to flap and another one when it stopped. *BUT* this rather means that your thresholds are too low or just not optimal aligned with your environment and the flapping detection should not be the way to go here.

**Comment by winem** [comment]
@nisabek I just realized that my reference to #22 was wrong here. It should have been #23. My PR was not related to this ticket at all. But it might be legit to keep this ticket closed as there was no feedback for almost 2 months now. :)
