### ISSUE TITLE
How make it work with proxy ?

### ISSUE THREAD

**Issue by Quentinvarquet** [nisabek/icinga2-slack-notifications#28]
Hello,

I am trying to use your project and I would like to know if there is an easy way to make it work with a proxy ? (I can add a export http_proxy but I don't really like this solution :)) 

Thank you !

**Comment by nisabek** [comment]
Hi Quentin,

Thank you for being interested in using the project. I'm not sure I understand the question...proxy where?... if you mean accessing slack endpoint that is behind a proxy, there is a `slack_notifications_proxy` variable you can use...

Let me know if you meant something else.

Thanks and Regards,
Nune

**Comment by Quentinvarquet** [comment]
Hello,
Yes it was exactly my question :) Thank you i ll try it now

**Comment by Quentinvarquet** [comment]
Edit : It's working ! 

Thank you again
