### ISSUE TITLE
Multiple Slack Webhooks

### ISSUE THREAD

**Issue by rochecompaan** [nisabek/icinga2-slack-notifications#30]
Thanks for a great plugin!

I manage server clusters for different customers. I have a webhook in place that is enabled for all servers across all clusters.

I would like to set up additional customer-specific webhooks where the DevOps team for that customer receives slack notifications for their servers.

How would you advise one setup different slack webhooks for different groups?

**Comment by nisabek** [comment]
Hi @rochecompaan thanks for using it! :)

If I understand correctly that would mean you have different Service/Host templates for each customer correct?..
If my memory serves me right...I think setting the webhook url in the template will override the default one...but you would need to try it out

here is a closed issue that was asking for a similar feature, but I didn't hear back from the OP...maybe you can give it a try and let us all know :)

https://github.com/nisabek/icinga2-slack-notifications/issues/14

**Comment by rochecompaan** [comment]
Hi @nisabek, thanks for your reply!

I use the same Service/Host templates for all customers. The only difference is that they have different notification groups.  I was considering to just duplicate the slack notification command and rename it but that doesn't feel like an optimal solution.

**Comment by nisabek** [comment]
> different notification groups
as in different     users = [ "icingaadmin" ] ?...

**Comment by rochecompaan** [comment]
> > different notification groups
> 
> as in different from users = [ "icingaadmin" ] ?...

Yes, for some customers it is [ "icingaadmin", "customerX" ] and for others it is ["icingaadmin", "customerY"].

**Comment by nisabek** [comment]
hmm..you definitely don't need to duplicate the whole slack notification command...
the `users` come from `slack-notifications-default-configuration` (in file `slack-notifications-configuration.conf`) which is imported into `slack-notifications-user-configuration`
... I think if you change it in `slack-notifications-user-configuration` it will override the imported one... if so, you could have `slack-notifications-user-configuration` per client

**Comment by rochecompaan** [comment]
Ok, let me try that and I promise I'll report back :-)

**Comment by rochecompaan** [comment]
This is the default template and rule hierarchy:

![image](https://user-images.githubusercontent.com/784273/81055701-83db9d00-8ec9-11ea-97f8-cec5bc9ac6d0.png)

I created all the config sections marked with a "+":
![image](https://user-images.githubusercontent.com/784273/81057000-e3d34300-8ecb-11ea-9916-a3e4650973e1.png)

The above changes now send two notifications two my main original slack channel so I suspect I have to add default configurations for services and hosts that are customer-specific too.

**Comment by rochecompaan** [comment]
I managed to simplify my config to the following and it is working beautifully now:

```
template Notification "slack-notifications-CUSTOMER-configuration" {
    import "slack-notifications-default-configuration"

    vars.slack_notifications_webhook_url = "<SLACK WEBHOOK URL>"
    vars.slack_notifications_icinga2_base_url = "<SLACK BASE URL>"
}

template Notification "slack-notifications-CUSTOMER-configuration-hosts" {
    import "slack-notifications-CUSTOMER-configuration"
    command = "slack-notifications-command"
    states = [ Up, Down ]
}

template Notification "slack-notifications-CUSTOMER-configuration-services" {
    import "slack-notifications-CUSTOMER-configuration"
    command = "slack-notifications-command"
    states = [ OK, Warning, Critical, Unknown ]
}

apply Notification "slack-notifications-notification-CUSTOMER-hosts" to Host {
  import "slack-notifications-CUSTOMER-configuration-hosts"

  assign where host.vars.slack_notifications == "enabled" && match("*.customerdomain.com", host.name)
}

apply Notification "slack-notifications-notification-CUSTOMER-services" to Service {
  import "slack-notifications-CUSTOMER-configuration-services"

  assign where service.vars.slack_notifications == "enabled" && match("*.customerdomain.com", host.name)
}
```

Thanks for your guidance!

**Comment by nisabek** [comment]
Thanks @rochecompaan for trying out and letting us know! Best wishes! :)
