### ISSUE TITLE
[Contribution] Icinga Director solution!

### ISSUE THREAD

**Issue by jwhitbread** [nisabek/icinga2-slack-notifications#32]
Hey @nisabek,

Great tool, thanks for making it! I just got it working after a long 4 hours of essentially learning icinga director too! I've noticed there hasn't really been any descriptive solutions for getting it to work on icinga director, so here is what I did:

* Use the git version, not the debian package.
* Add all three files into your global_templates directory e.g /etc/icinga2/zones.d/global_templates/. (I believe these can also be put into your director/master directory)
* Follow the above tutorial with editing said files and permissions.
* Add the vars.slack_notifications = "enabled" to the relevant templates or directly to the host/service objects.
* Restart icinga2 - systemctl restart icinga2.

* Navigate over to your icinga web interface > Icinga director on the left > Deployments
* This should notify you that you have a change, click deploy. If it doesn't then on the same page navigate to Render config > Deploy anyways.
* Check the console output of the deployment, green tick = good! Go double check your hosts and services are picking up the new variable and then give it a test!

I hope this helps!

**Comment by nisabek** [comment]
Hey @jwhitbread  - Thanks a lot for putting these together! I added them to the README. 
Happy new year too! :)
