### ISSUE TITLE
Icinga unable to check on these files

### ISSUE THREAD

**Issue by ananthaa-advisory** [nisabek/icinga2-slack-notifications#6]
Greetings,

I cloned the GIT repo of yours and unable to start ICINGA2 service now.

root@sony-VPCEH25EN:/etc/icinga2# service icinga2 status
====================

● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-07-25 20:54:31 IST; 1s ago
  Process: 1481 ExecStart=/usr/sbin/icinga2 daemon -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 1415 ExecStartPre=/usr/lib/icinga2/prepare-dirs /usr/lib/icinga2/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 1481 (code=exited, status=1/FAILURE)

Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]: Location: in /etc/icinga2/icinga2.conf: 63:1-63:26
Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]: /etc/icinga2/icinga2.conf(61):  * directory. Each of these files must have the file e
Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]: /etc/icinga2/icinga2.conf(62):  */
Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]: /etc/icinga2/icinga2.conf(63): include_recursive "conf.d"
Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]: /etc/icinga2/icinga2.conf(64):
Jul 25 20:54:31 sony-VPCEH25EN.example.com icinga2[1481]: /etc/icinga2/icinga2.conf(65):
=====================

It looks like ICINGA unable to read anything,, if you create one more extra directory under /etc/icinga2/conf.d/ directory. 

I have placed the right permission to this slack-notifications directory:

drwxr-x--- 2 root   root   4096 Jul 25 20:42 slack-notifications

For  all the configuration files under /etc/icinga/conf.d/slack-notifications:

total 20
-rw-r--r-- 1 root root 6311 Jul 25 20:38 slack-notifications-command.conf
-rw-r--r-- 1 root root  647 Jul 25 20:38 slack-notifications-user-configuration.conf.template
-rw-r--r-- 1 root root  641 Jul 25 20:40 slack-notifications-user-configuration.conf
-rw-r--r-- 1 root root 1819 Jul 25 20:42 slack-notifications-configuration.conf

====================

Please help me on where I am going wrong. Thanks

Aravind

**Comment by Hipska** [comment]
What are the permissions of `/etc/icinga/conf.d/`?

**Comment by rhazdon** [comment]
Hi @Hipska:

My permissions for `/etc/icinga2/conf.d` are `744`.

**Comment by Hipska** [comment]
I was asking to the creator of this issue @ananthaa-advisory. Trying to solve his issue.

Could you also tell us what version of Icinga you are running?

**Comment by nisabek** [comment]
Hi, 
Sorry for late response and thanks for stepping in @Hipska 
Probably the issue is with configuring the permissions when installing using git
https://github.com/nisabek/icinga2-slack-notifications#installation-using-git
Please check step 3 in above section

Let us know how it goes @ananthaa-advisory 

Regards,
Nune

**Comment by ananthaa-advisory** [comment]
Hi Thanks for reply.

Some of my notifications are still not coming through slack.  May be my  host/service template has some issues. Can you help

**Comment by Hipska** [comment]
So the issue with "Icinga unable to check on these files" is resolved and thus can be closed?

**Comment by nisabek** [comment]
please let me know if this requires attention. Seems fixed...
